# Generated by Django 4.2.7 on 2026-01-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Rental Management System', max_length=200)),
                ('business_email', models.EmailField(default='admin@rental.com', max_length=254)),
                ('business_phone', models.CharField(blank=True, max_length=20)),
                ('min_rental_days', models.PositiveIntegerField(default=1)),
                ('max_rental_days', models.PositiveIntegerField(default=365)),
                ('late_return_penalty_percentage', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('tax_name', models.CharField(default='GST', max_length=50)),
                ('security_deposit_percentage', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
