# Generated by Django 4.2.7 on 2026-01-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_coupon_quotation_discount_amount_couponusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationline',
            name='period_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price for selected period', max_digits=10),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='rental_period_type',
            field=models.CharField(choices=[('HOURLY', 'Per Hour'), ('DAILY', 'Per Day'), ('WEEKLY', 'Per Week'), ('MONTHLY', 'Per Month'), ('YEARLY', 'Per Year')], default='DAILY', max_length=10),
        ),
    ]
