# Generated by Django 4.2.7 on 2026-01-31 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productattribute_productattributevalue_and_more'),
        ('rentals', '0003_quotationline_period_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationline',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_lines', to='products.productvariant'),
        ),
    ]
