# Generated by Django 4.2.7 on 2026-01-31 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('HOURLY', 'Per Hour'), ('DAILY', 'Per Day'), ('WEEKLY', 'Per Week'), ('MONTHLY', 'Per Month'), ('YEARLY', 'Per Year')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this period', max_digits=10)),
                ('is_default', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_periods', to='products.product')),
            ],
            options={
                'ordering': ['product', 'period_type'],
                'unique_together': {('product', 'period_type')},
            },
        ),
    ]
