# Generated by Django 4.2.7 on 2026-01-31 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rentalperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_type', models.CharField(choices=[('RADIO', 'Radio Buttons'), ('PILLS', 'Pills'), ('SELECT', 'Dropdown'), ('COLOR', 'Color Swatches')], default='RADIO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('color_code', models.CharField(blank=True, help_text='Hex color code for color attributes', max_length=7, null=True)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, help_text='Additional price for this variant', max_digits=10)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.productattribute')),
            ],
            options={
                'ordering': ['attribute', 'value'],
                'unique_together': {('attribute', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Price difference from base product (can be negative)', max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_variants/')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariantAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productattributevalue')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='products.productvariant')),
            ],
            options={
                'unique_together': {('variant', 'attribute_value')},
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=True, help_text='Must customer select this attribute?')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_lines', to='products.product')),
            ],
            options={
                'ordering': ['product', 'attribute'],
                'unique_together': {('product', 'attribute')},
            },
        ),
    ]
